// export const ADD_TRIP = 'ADD_TRIP';

export default constants = {
  ADD_RECOMMENDATION: "ADD_RECOMMENDATION",
  DELETE_RECOMMENDATION: "DELETE_RECOMMENDATION",
  EDIT_RECOMMENDATION: "EDIT_RECOMMENDATION",
  UPDATE_NEW_RECOMMENDATION: "UPDATE_NEW_RECOMMENDATION",
};