let types;
export default types = {
  ADD_TIMEBLOCK: 'ADD_TIMEBLOCK',
  ADD_VOTE: 'ADD_YESVOTE',
  ADD_COMMENT: 'ADD_COMMENT',
  EDIT_TIMEBLOCK: 'EDIT_TIMEBLOCK',
  EDIT_VOTE: 'EDIT_YESVOTE',
  EDIT_COMMENT: 'EDIT_COMMENT',
  DELETE_TIMEBLOCK: 'DELETE_TIMEBLOCK',
  DELETE_COMMENT: 'DELETE_COMMENT'
}